const data = {
  products: [
    {
      name: "Soft Graphic T-Shirt",
      slug: "soft-tshirt-0",
      category: "shirts",
      image: "/images/tshirt-1.jpg",
      price: 35,
      brand: "Nike",
      rating: 4.7,
      numReviews: 7,
      countInStock: 15,
      description: "A popular t-shirt",
    },
    {
      name: "Soft Graphic T-Shirt",
      slug: "soft-tshirt-1",
      category: "shirts",
      image: "/images/tshirt-2.jpg",
      price: 65,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 7,
      countInStock: 15,
      description: "A popular t-shirt",
    },
    {
      name: "Soft Pants",
      slug: "soft-pants-1",
      category: "pants",
      image: "/images/pants-2.jpg",
      price: 65,
      brand: "Nike",
      rating: 4.7,
      numReviews: 7,
      countInStock: 0,
      description: "A popular t-shirt",
    },
    {
      name: "Soft Pants",
      slug: "soft-pants-2",
      category: "pants",
      image: "/images/tshirt-1.jpg",
      price: 95,
      brand: "Oliver",
      rating: 4.7,
      numReviews: 7,
      countInStock: 15,
      description: "A popular t-shirt",
    },
    {
      name: "Soft Graphic T-Shirt",
      slug: "soft-tshirt-3",
      category: "shirts",
      image: "/images/tshirt-3.jpg",
      price: 75,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 7,
      countInStock: 15,
      description: "A popular t-shirt",
    },
    {
      name: "Soft Graphic T-Shirt",
      slug: "soft-tshirt-4",
      category: "shirts",
      image: "/images/tshirt-1.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.7,
      numReviews: 7,
      countInStock: 15,
      description: "A popular t-shirt",
    },
  ],
}

export default data
