import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "Abdullah",
      email: "admin@cornermall.com",
      password: bcrypt.hashSync("admin@cornermall@123"),
      isAdmin: true,
    },
    {
      name: "Ahmed",
      email: "ahmed@gmail.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Soft Graphic T-Shirt",
      slug: "soft-tshirt",
      category: "clothes",
      image: "/images/clothes/tshirt-1.jpg",
      price: 35,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      countInStock: 10,
      description: "A popular t-shirt",
    },
    {
      name: "Striped Print Shirt",
      slug: "striped-shirt",
      category: "clothes",
      image: "/images/clothes/tshirt-2.jpg",
      price: 65,
      brand: "Adidas",
      rating: 3.7,
      numReviews: 21,
      countInStock: 10,
      description: "A popular t-shirt",
    },
    {
      name: "Flap Pocket Shirt",
      slug: "flap-shirt",
      category: "clothes",
      image: "/images/clothes/tshirt-3.jpg",
      price: 25,
      brand: "Nike",
      rating: 4.2,
      numReviews: 12,
      countInStock: 0,
      description: "A popular t-shirt",
    },
    {
      name: "Geo Print Polo Shirt",
      slug: "polo-shirt",
      category: "clothes",
      image: "/images/clothes/tshirt-4.jpg",
      price: 23,
      brand: "Oliver",
      rating: 4.8,
      numReviews: 7,
      countInStock: 10,
      description: "A popular t-shirt",
    },
    {
      name: "Slant Pocket Skinny Pants",
      slug: "skinny-pants",
      category: "clothes",
      image: "/images/clothes/pants-1.jpg",
      price: 67,
      brand: "Adidas",
      rating: 4.8,
      numReviews: 2,
      countInStock: 10,
      description: "A popular pants",
    },
    {
      name: "Print Straight Leg Pants",
      slug: "print-pants",
      category: "clothes",
      image: "/images/clothes/pants-2.jpg",
      price: 40,
      brand: "Nike",
      rating: 4.6,
      numReviews: 9,
      countInStock: 10,
      description: "A popular pants",
    },
    {
      name: "Pocket Cargo Pants",
      slug: "pocket-cargo-pants",
      category: "clothes",
      image: "/images/clothes/pants-3.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.4,
      numReviews: 15,
      countInStock: 10,
      description: "A popular pants",
    },
    {
      name: "Space Dye Tailored Pants",
      slug: "tailored-pants",
      category: "clothes",
      image: "/images/clothes/pants-4.jpg",
      price: 44,
      brand: "Adidas",
      rating: 3.6,
      numReviews: 9,
      countInStock: 10,
      description: "A popular pants",
    },
    {
      name: "iPhone 13 Pro Max",
      slug: "iphone-13-pro-max",
      category: "mobiles",
      image: "/images/mobiles/iphone-13-pro-max.jpg",
      price: 1050,
      brand: "Apple",
      rating: 4.9,
      numReviews: 85,
      countInStock: 10,
      description: "A popular iPhone",
    },
    {
      name: "iPhone 12",
      slug: "iphone-12",
      category: "mobiles",
      image: "/images/mobiles/iphone-12.jpg",
      price: 625,
      brand: "Apple",
      rating: 4.9,
      numReviews: 42,
      countInStock: 10,
      description: "A popular iPhone",
    },
    {
      name: "Samsung Galaxy S22 Ultra",
      slug: "samsung-s22-ultra",
      category: "mobiles",
      image: "/images/mobiles/samsung-s22-ultra.jpg",
      price: 1125,
      brand: "Samsung",
      rating: 4.8,
      numReviews: 61,
      countInStock: 10,
      description: "A popular mobile",
    },
    {
      name: "Samsung Galaxy A52",
      slug: "samsung-galaxy-a52",
      category: "mobiles",
      image: "/images/mobiles/samsung-galaxy-a52.jpg",
      price: 415,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 20,
      countInStock: 10,
      description: "A popular mobile",
    },
    {
      name: "Huawei P30 Pro",
      slug: "huawei-p30-pro",
      category: "mobiles",
      image: "/images/mobiles/huawei-p30-pro.jpg",
      price: 950,
      brand: "Huawei",
      rating: 4.9,
      numReviews: 62,
      countInStock: 10,
      description: "A popular mobile",
    },
    {
      name: "Huawei Y9 2019",
      slug: "huawei-y9-2019",
      category: "mobiles",
      image: "/images/mobiles/huawei-y9-2019.jpg",
      price: 320,
      brand: "Huawei",
      rating: 4.2,
      numReviews: 62,
      countInStock: 10,
      description: "A popular mobile",
    },
    {
      name: "Oppo Reno 3",
      slug: "oppo-reno-3",
      category: "mobiles",
      image: "/images/mobiles/oppo-reno-3.jpg",
      price: 250,
      brand: "Oppo",
      rating: 4.1,
      numReviews: 12,
      countInStock: 10,
      description: "A popular mobile",
    },
    {
      name: "Oppo A93",
      slug: "oppo-a93",
      category: "mobiles",
      image: "/images/mobiles/oppo-a93.jpg",
      price: 280,
      brand: "Oppo",
      rating: 4.0,
      numReviews: 11,
      countInStock: 10,
      description: "A popular mobile",
    },
    {
      name: "Apple MacBook Pro 2021",
      slug: "apple-macBook-pro-2021",
      category: "laptops",
      image: "/images/laptops/apple-macBook-pro-2021.jpg",
      price: 1240,
      brand: "Apple",
      rating: 4.9,
      numReviews: 25,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "Apple MacBook Air",
      slug: "apple-macBook-air",
      category: "laptops",
      image: "/images/laptops/apple-macBook-air.jpg",
      price: 450,
      brand: "Apple",
      rating: 4.8,
      numReviews: 18,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "HUAWEI MateBook 14 2021",
      slug: "huawei-mateBook-14-2021",
      category: "laptops",
      image: "/images/laptops/huawei-mateBook-14-2021.jpg",
      price: 925,
      brand: "Huawei",
      rating: 4.9,
      numReviews: 32,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "Huawei MmateBook X Pro 2022",
      slug: "huawei-matebook-x-pro-2022",
      category: "laptops",
      image: "/images/laptops/huawei-matebook-x-pro-2022.jpg",
      price: 2050,
      brand: "Huawei",
      rating: 4.7,
      numReviews: 14,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "Acer Predator Helios 300",
      slug: "acer-predator-helios-300",
      category: "laptops",
      image: "/images/laptops/acer-predator-helios-300.jpg",
      price: 1490,
      brand: "Acer",
      rating: 4.9,
      numReviews: 24,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "Asus GX550L",
      slug: "asus-gx550l",
      category: "laptops",
      image: "/images/laptops/asus-gx550l.jpg",
      price: 3200,
      brand: "Asus",
      rating: 4.9,
      numReviews: 22,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "Lenovo IdeaPad Y700",
      slug: "lenovo-ideapad-y700",
      category: "laptops",
      image: "/images/laptops/lenovo-ideapad-y700.jpg",
      price: 1105,
      brand: "Lenovo",
      rating: 4.5,
      numReviews: 9,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "Dell G15 5510",
      slug: "dell-g15-5510",
      category: "laptops",
      image: "/images/laptops/dell-g15-5510.jpg",
      price: 1400,
      brand: "Dell",
      rating: 4.6,
      numReviews: 7,
      countInStock: 10,
      description: "A popular laptop",
    },
  ],
}

export default data
